#pragma once

BEGIN(Engine)

enum EMaterial
{
    EMATERIAL_NONE,
    EMATERIAL_DIFFUSE,
    EMATERIAL_SPECULAR,
    EMATERIAL_AMBIENT,
    EMATERIAL_EMISSIVE,
    EMATERIAL_HEIGHT,
    EMATERIAL_NORMALS,
    EMATERIAL_SHININESS,
    EMATERIAL_OPACITY,
    EMATERIAL_DISPLACEMENT,
    EMATERIAL_LIGHTMAP,
    EMATERIAL_REFLECTION,
    EMATERIAL_BASE_COLOR,
    EMATERIAL_NORMAL_CAMERA,
    EMATERIAL_EMISSION_COLOR,
    EMATERIAL_METALNESS,
    EMATERIAL_DIFFUSE_ROUGHNESS,
    EMATERIAL_AMBIENT_OCCLUSION,
    EMATERIAL_UNKNOWN,
    EMATERIAL_SHEEN,
    EMATERIAL_CLEARCOAT,
    EMATERIAL_TRANSMISSION,
    EMATERIAL_MAYA_BASE,
    EMATERIAL_MAYA_SPECULAR,
    EMATERIAL_MAYA_SPECULAR_COLOR,
    EMATERIAL_MAYA_SPECULAR_ROUGHNESS,
};

#define MATERIAL_MAX EMATERIAL_MAYA_SPECULAR_ROUGHNESS

END